name: flutter_deeplinkly
description: A lightweight Flutter plugin for deep linking, deferred deep linking, install referrer tracking, and advanced attribution.
version: 1.1.2
homepage:
  https://github.com/deeplinkly/flutter_deeplinkly
repository: https://github.com/deeplinkly/flutter_deeplinkly
issue_tracker: https://github.com/deeplinkly/flutter_deeplinkly/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.10.0"


dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.deeplinkly.flutter_deeplinkly
        pluginClass: FlutterDeeplinklyPlugin
      ios:
        pluginClass: FlutterDeeplinklyPlugin
